security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
                default_target_path: category
            logout:
                path: logout
                target: login

    access_control:
        - { path: ^/category, roles: "ROLE_USER" }
        - { path: ^/account, roles: "ROLE_USER" }